spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB   # Maximum file size for a single file
#      max-request-size: 50MB  # Maximum request size (total size of all files)
  springdoc:
    default-produces-media-type: application/json
  server:
    servlet:
      context-path: /api/v1/

